name: Release Drafter

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release_drafter:
    uses: khanh-company-1/github-workflows/.github/workflows/release-drafter.yml@main